version: "3.9"
services:
  web:
    container_name: front
    build: services/frontend
    ports:
      - "3000:3000"
    networks:
      - backend
    depends_on:
      - reader
      
  reader:
    container_name: back
    build: services/reader
    ports:
      - "8080:8080"
    networks:
      - backend

  writer:
    container_name: python
    build: services/writer
    ports:
      - "8081:8081"
    networks:
      - backend

  redis:
    container_name: redis
    image: redis:alpine
    networks:
      - backend

networks:
  backend:
    driver: bridge
